remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Brett Plemons | AI Engineering Portfolio
description: Software Engineering Manager transitioning to AI/ML leadership. Capstone portfolio showcasing Bayesian inference, Monte Carlo simulation, and modern software architecture.
